# The Final
![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Libraries

In [393]:
import numpy as np
import pandas as pd
import datetime as dt
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

pd.options.display.float_format = '{:.2f}'.format

## Functions

In [394]:
# selective call to function
class dataProfiling:

    def moreInfo(self, data):    
        # more data info
        print(f"MORE DATA INFO :")
        print("-" * 109)

        print(f"Data shape : {data.shape}\n")

        # counts no. total values in the data
        print(f"No. of values in the dataset : {data.size:,}")

        # counts no. of rows
        print(f"Total rows in the dataset : {len(data):,}")

        # counts no. of columns
        print(f"Total columns in the dataset : {len(data.columns):,}")

        # counts no. of missing values
        print(f"\nTotal null values : {data.isnull().sum().sum():,}")

        # counts no. of duplicates
        countDuplicates = data.duplicated().sum()
        print(f"Total duplicated rows : {format(countDuplicates, ',')}")

        # compute missing/duplicates ratio
        print(f"\nRATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :")
        print("-" * 109)

        # ratio for missing values
        isnull_ratio = (data.isnull().sum().sum() / data.size) * 100

        # ratio for duplicated values
        dup_ratio = (data.duplicated().sum() / len(data)) * 100

        # return results
        print(f"\nPercentage of null values in the data : {round(isnull_ratio, 2)}%")
        print(f"Percentage of duplicates in the data : {round(dup_ratio, 2)}%\n")

        # count unique values per column
        print(f"\nNUMBER OF UNIQUE VALUES PER COLUMN :")
        print("-" * 109)

        for column in data.columns:
            uniqueVal = data[column].nunique()
            print(f"Total unique values for column {column}: {uniqueVal:,}")

    def valueCounts(self, data):
        # count no. of values per column
        print(f"\nCOUNT VALUES FOR EACH COLUMN :")
        print("-" * 109)
        for column in data.columns:
            countValues = data[column].value_counts(dropna=False).to_frame()
            totalValues = data[column].count()
            print(f"VALUE_COUNTS for column '{column}' : {len(countValues)} rows, {totalValues} values in Total\n")
            display(countValues)
            print("-" * 109)

    def nullColumns(self, data):
        # displays no. of missing values per column
        print(f"\nTOTAL MISSING VALUES FOR EACH COLUMN :")
        display(data.isnull().sum().to_frame().rename(columns={0: "MISSING VALUES"}))
        print("\n")

    def nullGroupby(self, data, column):
        # displays no. of missing values per category
        print(f"\nTOTAL MISSING VALUES PER COLUMN FOR EACH UNIQUE VALUE :")        
        display(data.isna().groupby(data[column]).sum())

        print("\n")
    def visualizeNulls(self, data):
        # visualize missing values
        print(f"VISAULIZE MISSNG VALUES :")
        print("-" * 109)

        # method 1
        print("METHOD 1")
        sns.heatmap(data.isnull().T,
                    xticklabels=False,
                    cmap="viridis",
                    cbar_kws={"label": "Missing Values"})

        plt.tight_layout()
        plt.show()
        print("\n")

        # method 2
        print("METHOD 2")
        plt.imshow(data.isna(), aspect="auto", interpolation="nearest", cmap="gray")
        plt.xlabel("Column Number")
        plt.ylabel("Sample Number");
        print("\n")

    def nullFeature(self, data, column):
        # displays rows where missing values are found of a specific column 
        print(f"DISPLAYS ROWS WHERE MISSING VALUES ARE FOUND OF A SPECIFIC FEATURE:")
        display(data[data[column].isna()])
        print("\n")

    def nullData(self, data):
        # displays rows where missing values are found
        print(f"DISPLAYS ROWS WHERE MISSING VALUES ARE FOUND :")
        display(data[data.isnull().any(axis=1)])
        print("\n")

    def allStats(self, data):
        # overall descerptive analysis (nuemrical and categorical)
        print(f"FULL DATA DESCRIPTIVE STATISTICS :")
        print("-" * 109)
        display(data.describe(include="all"))
        print("\n")

    def descriptiveData(self, data):
        # do quick descriptive statistics
        print(f"QUICK DESCRIPTIVE ANALYSIS :")
        print("-" * 109)
        display(data.describe())
        print("\n")

    def nonNumericStats(self, data):
        # categorical statistics
        print(f"NON-NUMERICAL STATISTICS :")
        print("-" * 109)
        display(data.describe(exclude="number"))
        print("\n")

    def uniqueColumns(self, data):
        # view all unique values for each column
        print(f"UNIQUE VALUES FOR EACH COLUMN :")
        print("-" * 109)

        for column in data.columns:
            uniqueValues = data[column].unique()
            uniqueCount = data[column].nunique()
            print(f"UNIQUE VALUES for column '{column}' : {len(uniqueValues)} including NaN values, {uniqueCount} excluding Nan values\n")
            print(f"{uniqueValues}\n")
            print("-" * 109)

    def plotUniques(self, data):
        # for each numerical feature compute number of unique entries
        unique_values = data.select_dtypes(include="number").nunique().sort_values()

        # plot information with y-axis in log-scale
        unique_values.plot.bar(logy=False, title="No. of unique values per feature", figsize=(25,7))
        plt.xticks(rotation=0)
        plt.tight_layout()
        plt.show()

# instance of the dataProfiling class
profiler = dataProfiling()

## Load dataset

In [395]:
data = pd.read_csv("OnlineRetail.csv", encoding="WINDOWS-1252")
data = data[["InvoiceNo", "InvoiceDate", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Country"]]

backup = data.copy()

display(data.head())

InvoiceNo     InvoiceDate StockCode                          Description  \
0    536365  12/1/2010 8:26    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1    536365  12/1/2010 8:26     71053                  WHITE METAL LANTERN   
2    536365  12/1/2010 8:26    84406B       CREAM CUPID HEARTS COAT HANGER   
3    536365  12/1/2010 8:26    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4    536365  12/1/2010 8:26    84029E       RED WOOLLY HOTTIE WHITE HEART.   

   Quantity  UnitPrice  CustomerID         Country  
0         6       2.55    17850.00  United Kingdom  
1         6       3.39    17850.00  United Kingdom  
2         8       2.75    17850.00  United Kingdom  
3         6       3.39    17850.00  United Kingdom  
4         6       3.39    17850.00  United Kingdom

## Investigate data

Let's check our data types first so we can fix them first before moving forward

In [396]:
display(data.dtypes)

InvoiceNo       object
InvoiceDate     object
StockCode       object
Description     object
Quantity         int64
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

There are few changes to do in our data:
- InvoiceNo to int64
- InvoiceDate to datetime[ns]
- Add Revenue column
- CustomerID to int64

Let's investigate further

In [397]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (541909, 8)

No. of values in the dataset : 4,335,272
Total rows in the dataset : 541,909
Total columns in the dataset : 8

Total null values : 136,534
Total duplicated rows : 5,268

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 3.15%
Percentage of duplicates in the data : 0.97%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 25,900
Total unique values for column InvoiceDate: 23,260
Total unique values for column StockCode: 4,070
Total unique values for column Description: 4,223
Total unique values for column Quantity: 722
Total unique values for column

We have 5,268 duplicates out of 541,909 rows. <br>
Let's focus on that first

# Clean data
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Duplicates

In [398]:
data[data.duplicated(keep=False)]

InvoiceNo      InvoiceDate StockCode                       Description  \
485       536409  12/1/2010 11:45     22111      SCOTTIE DOG HOT WATER BOTTLE   
489       536409  12/1/2010 11:45     22866     HAND WARMER SCOTTY DOG DESIGN   
494       536409  12/1/2010 11:45     21866       UNION JACK FLAG LUGGAGE TAG   
517       536409  12/1/2010 11:45     21866       UNION JACK FLAG LUGGAGE TAG   
521       536409  12/1/2010 11:45     22900   SET 2 TEA TOWELS I LOVE LONDON    
...          ...              ...       ...                               ...   
541675    581538  12/9/2011 11:34     22068       BLACK PIRATE TREASURE CHEST   
541689    581538  12/9/2011 11:34     23318    BOX OF 6 MINI VINTAGE CRACKERS   
541692    581538  12/9/2011 11:34     22992            REVOLVER WOODEN RULER    
541699    581538  12/9/2011 11:34     22694                      WICKER STAR    
541701    581538  12/9/2011 11:34     23343      JUMBO BAG VINTAGE CHRISTMAS    

        Quantity  UnitPrice  CustomerID         Country  
485            1       4.95    17908.00  United Kingdom  
489            1       2.10    17908.00  United Kingdom  
494            1       1.25    17908.00  United Kingdom  
517            1       1.25    17908.00  United Kingdom  
521            1       2.95    17908.00  United Kingdom  
...          ...        ...         ...             ...  
541675         1       0.39    14446.00  United Kingdom  
541689         1       2.49    14446.00  United Kingdom  
541692         1       1.95    14446.00  United Kingdom  
541699         1       2.10    14446.00  United Kingdom  
541701         1       2.08    14446.00  United Kingdom  

[10147 rows x 8 columns]

In [399]:
print(f"Number of rows with duplicates: {len(data):,}")
print(f"Number of duplicates: {data.duplicated().sum():,}")
print(f"Number of rows without duplicates: {len(data.drop_duplicates()):,}\n")

data.drop_duplicates(inplace=True)
print(f"Verify results (dataset after removing duplicates): {len(data):,}")

Number of rows with duplicates: 541,909
Number of duplicates: 5,268
Number of rows without duplicates: 536,641

Verify results (dataset after removing duplicates): 536,641


Duplicate removals went well with coherent results, bsaed on the information previously (_cf_ `profiler.moreInfo(data)`). <br>
Now, let's go ahead and work on the missing values

## Missing values

In [400]:
profiler.nullColumns(data)


TOTAL MISSING VALUES FOR EACH COLUMN :


MISSING VALUES
InvoiceNo                 0
InvoiceDate               0
StockCode                 0
Description            1454
Quantity                  0
UnitPrice                 0
CustomerID           135037
Country                   0

In [401]:
display(profiler.nullFeature(data, "CustomerID"))

print("Unique values for CustomerID with InvoiceNo 581498")
data.loc[data["InvoiceNo"] == "581498"]["CustomerID"].unique()

DISPLAYS ROWS WHERE MISSING VALUES ARE FOUND OF A SPECIFIC FEATURE:


InvoiceNo      InvoiceDate StockCode                      Description  \
622       536414  12/1/2010 11:52     22139                              NaN   
1443      536544  12/1/2010 14:32     21773  DECORATIVE ROSE BATHROOM BOTTLE   
1444      536544  12/1/2010 14:32     21774  DECORATIVE CATS BATHROOM BOTTLE   
1445      536544  12/1/2010 14:32     21786               POLKADOT RAIN HAT    
1446      536544  12/1/2010 14:32     21787            RAIN PONCHO RETROSPOT   
...          ...              ...       ...                              ...   
541536    581498  12/9/2011 10:26    85099B          JUMBO BAG RED RETROSPOT   
541537    581498  12/9/2011 10:26    85099C   JUMBO  BAG BAROQUE BLACK WHITE   
541538    581498  12/9/2011 10:26     85150    LADIES & GENTLEMEN METAL SIGN   
541539    581498  12/9/2011 10:26     85174                S/4 CACTI CANDLES   
541540    581498  12/9/2011 10:26       DOT                   DOTCOM POSTAGE   

        Quantity  UnitPrice  CustomerID         Country  
622           56       0.00         NaN  United Kingdom  
1443           1       2.51         NaN  United Kingdom  
1444           2       2.51         NaN  United Kingdom  
1445           4       0.85         NaN  United Kingdom  
1446           2       1.66         NaN  United Kingdom  
...          ...        ...         ...             ...  
541536         5       4.13         NaN  United Kingdom  
541537         4       4.13         NaN  United Kingdom  
541538         1       4.96         NaN  United Kingdom  
541539         1      10.79         NaN  United Kingdom  
541540         1    1714.17         NaN  United Kingdom  

[135037 rows x 8 columns]

None

Unique values for CustomerID with InvoiceNo 581498


array([nan])

In [402]:
profiler.nullFeature(data, "Description")

DISPLAYS ROWS WHERE MISSING VALUES ARE FOUND OF A SPECIFIC FEATURE:


InvoiceNo      InvoiceDate StockCode Description  Quantity  UnitPrice  \
622       536414  12/1/2010 11:52     22139         NaN        56       0.00   
1970      536545  12/1/2010 14:32     21134         NaN         1       0.00   
1971      536546  12/1/2010 14:33     22145         NaN         1       0.00   
1972      536547  12/1/2010 14:33     37509         NaN         1       0.00   
1987      536549  12/1/2010 14:34    85226A         NaN         1       0.00   
...          ...              ...       ...         ...       ...        ...   
535322    581199  12/7/2011 18:26     84581         NaN        -2       0.00   
535326    581203  12/7/2011 18:31     23406         NaN        15       0.00   
535332    581209  12/7/2011 18:35     21620         NaN         6       0.00   
536981    581234  12/8/2011 10:33     72817         NaN        27       0.00   
538554    581408  12/8/2011 14:06     85175         NaN        20       0.00   

        CustomerID         Country  
622            NaN  United Kingdom  
1970           NaN  United Kingdom  
1971           NaN  United Kingdom  
1972           NaN  United Kingdom  
1987           NaN  United Kingdom  
...            ...             ...  
535322         NaN  United Kingdom  
535326         NaN  United Kingdom  
535332         NaN  United Kingdom  
536981         NaN  United Kingdom  
538554         NaN  United Kingdom  

[1454 rows x 8 columns]

We will proceed in dropping the missing values which account for 3.15% in our second data.

In [403]:
print(f"Number of rows with null values: {len(data):,}")
print(f"Number of null values: {data.isnull().sum().sum():,}")
print(f"Number of rows without null values: {len(data.dropna()):,}\n")

data.dropna(inplace=True)
print(f"Verify results (dataset after removing null values): {len(data):,}")

Number of rows with null values: 536,641
Number of null values: 136,491
Number of rows without null values: 401,604

Verify results (dataset after removing null values): 401,604


Let's check our data

In [404]:
profiler.nullColumns(data)


TOTAL MISSING VALUES FOR EACH COLUMN :


MISSING VALUES
InvoiceNo                 0
InvoiceDate               0
StockCode                 0
Description               0
Quantity                  0
UnitPrice                 0
CustomerID                0
Country                   0

## Data types

Let's fix data types now. <br>
Then we'll investigate the difference between `Description` and `StockCode` columns in both data

In [405]:
data.dtypes

InvoiceNo       object
InvoiceDate     object
StockCode       object
Description     object
Quantity         int64
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

It might be that the InvoiceNo column contains alphanumeric values instead of only numeric ones. Let's verify our theory.

In [406]:
non_numeric_invoice = data[~data['InvoiceNo'].apply(lambda x: str(x).isnumeric())]
display(non_numeric_invoice)

InvoiceNo      InvoiceDate StockCode                       Description  \
141      C536379   12/1/2010 9:41         D                          Discount   
154      C536383   12/1/2010 9:49    35004C   SET OF 3 COLOURED  FLYING DUCKS   
235      C536391  12/1/2010 10:24     22556    PLASTERS IN TIN CIRCUS PARADE    
236      C536391  12/1/2010 10:24     21984  PACK OF 12 PINK PAISLEY TISSUES    
237      C536391  12/1/2010 10:24     21983  PACK OF 12 BLUE PAISLEY TISSUES    
...          ...              ...       ...                               ...   
540449   C581490   12/9/2011 9:57     23144   ZINC T-LIGHT HOLDER STARS SMALL   
541541   C581499  12/9/2011 10:28         M                            Manual   
541715   C581568  12/9/2011 11:57     21258        VICTORIAN SEWING BOX LARGE   
541716   C581569  12/9/2011 11:58     84978  HANGING HEART JAR T-LIGHT HOLDER   
541717   C581569  12/9/2011 11:58     20979     36 PENCILS TUBE RED RETROSPOT   

        Quantity  UnitPrice  CustomerID         Country  
141           -1      27.50    14527.00  United Kingdom  
154           -1       4.65    15311.00  United Kingdom  
235          -12       1.65    17548.00  United Kingdom  
236          -24       0.29    17548.00  United Kingdom  
237          -24       0.29    17548.00  United Kingdom  
...          ...        ...         ...             ...  
540449       -11       0.83    14397.00  United Kingdom  
541541        -1     224.69    15498.00  United Kingdom  
541715        -5      10.95    15311.00  United Kingdom  
541716        -1       1.25    17315.00  United Kingdom  
541717        -5       1.25    17315.00  United Kingdom  

[8872 rows x 8 columns]

In [407]:
data.loc[data["Quantity"] < 0]

InvoiceNo      InvoiceDate StockCode                       Description  \
141      C536379   12/1/2010 9:41         D                          Discount   
154      C536383   12/1/2010 9:49    35004C   SET OF 3 COLOURED  FLYING DUCKS   
235      C536391  12/1/2010 10:24     22556    PLASTERS IN TIN CIRCUS PARADE    
236      C536391  12/1/2010 10:24     21984  PACK OF 12 PINK PAISLEY TISSUES    
237      C536391  12/1/2010 10:24     21983  PACK OF 12 BLUE PAISLEY TISSUES    
...          ...              ...       ...                               ...   
540449   C581490   12/9/2011 9:57     23144   ZINC T-LIGHT HOLDER STARS SMALL   
541541   C581499  12/9/2011 10:28         M                            Manual   
541715   C581568  12/9/2011 11:57     21258        VICTORIAN SEWING BOX LARGE   
541716   C581569  12/9/2011 11:58     84978  HANGING HEART JAR T-LIGHT HOLDER   
541717   C581569  12/9/2011 11:58     20979     36 PENCILS TUBE RED RETROSPOT   

        Quantity  UnitPrice  CustomerID         Country  
141           -1      27.50    14527.00  United Kingdom  
154           -1       4.65    15311.00  United Kingdom  
235          -12       1.65    17548.00  United Kingdom  
236          -24       0.29    17548.00  United Kingdom  
237          -24       0.29    17548.00  United Kingdom  
...          ...        ...         ...             ...  
540449       -11       0.83    14397.00  United Kingdom  
541541        -1     224.69    15498.00  United Kingdom  
541715        -5      10.95    15311.00  United Kingdom  
541716        -1       1.25    17315.00  United Kingdom  
541717        -5       1.25    17315.00  United Kingdom  

[8872 rows x 8 columns]

Our theory was right. <br>


Upon examining the quantity values, we see some negative values. <br>
These negative values can be interpreted as refunds. <br><br>

Since analyzing refunds might be important later on, I have taken the step to store them in a separate dataframe (_later after data cleaning_) and eliminate them from the primary dataframe.

Let's focus on data types first. <br>
Columns to fix:
- InvoiceNo to int64 (_later just before separating dataRefund from our main data_)
- InvoiceDate to datetime[ns]
- Add Revenue column
- CustomerID to int64

In [408]:
data["InvoiceDate"] = pd.to_datetime(data["InvoiceDate"])
data["Revenue"] = round(data["Quantity"] * data["UnitPrice"], 2)
data["CustomerID"] = data["CustomerID"].astype(int)

data = data[["InvoiceNo", "InvoiceDate", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue", "CustomerID", "Country"]]
data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A   
1    536365 2010-12-01 08:26:00     71053   
2    536365 2010-12-01 08:26:00    84406B   
3    536365 2010-12-01 08:26:00    84029G   
4    536365 2010-12-01 08:26:00    84029E   

                           Description  Quantity  UnitPrice  Revenue  \
0   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55    15.30   
1                  WHITE METAL LANTERN         6       3.39    20.34   
2       CREAM CUPID HEARTS COAT HANGER         8       2.75    22.00   
3  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39    20.34   
4       RED WOOLLY HOTTIE WHITE HEART.         6       3.39    20.34   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17850  United Kingdom  
4       17850  United Kingdom

Let's verify once more

In [409]:
data.dtypes

InvoiceNo              object
InvoiceDate    datetime64[ns]
StockCode              object
Description            object
Quantity                int64
UnitPrice             float64
Revenue               float64
CustomerID              int64
Country                object
dtype: object

## StockCode and Description

In [410]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (401604, 9)

No. of values in the dataset : 3,614,436
Total rows in the dataset : 401,604
Total columns in the dataset : 9

Total null values : 0
Total duplicated rows : 0

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 22,190
Total unique values for column InvoiceDate: 20,460
Total unique values for column StockCode: 3,684
Total unique values for column Description: 3,896
Total unique values for column Quantity: 436
Total unique values for column UnitPrice: 

We were supposed to have one StockCode per item, <br>
but we have quite a difference of 212/213 unique values between StockCode and Description. <br>
Let's take a look into that right away!

### Description

In [411]:
# Identify the StockCode that have multiple Description
StockCode_Description_counts = data.groupby('StockCode')['Description'].nunique()

# Filter the StockCode that have multiple Description
StockCode_with_multiple_Description = StockCode_Description_counts[StockCode_Description_counts > 1]

# Show
StockCode_with_multiple_Description.to_frame().reset_index()

StockCode  Description
0      16156L            2
1      17107D            3
2       20622            2
3       20725            2
4       20914            2
..        ...          ...
208    85184C            2
209    85185B            2
210    90014A            2
211    90014B            2
212    90014C            2

[213 rows x 2 columns]

In [412]:
# Filter the original dataset based on StockCode that have multiple Description
filtered_data = data[data['StockCode'].isin(StockCode_with_multiple_Description.index)]

# View all columns for StockCode that have multiple Description
filtered_data = filtered_data.groupby(['StockCode', 'Description'])['Revenue'].sum().to_frame()

# Show
# pd.set_option("display.max_rows", None)
filtered_data.head()

Revenue
StockCode Description                                 
16156L    WRAP CAROUSEL                         157.50
          WRAP, CAROUSEL                         42.00
17107D    FLOWER FAIRY 5 DRAWER LINERS          150.45
          FLOWER FAIRY 5 SUMMER DRAW LINERS      15.30
          FLOWER FAIRY,5 SUMMER B'DRAW LINERS   267.75

Let's clean Description using NFX from NeatText Functions

#### NFX

In [413]:
# !pip install neattext

# Load Text Cleaning Pkgs
import neattext as nt # Method 1: OOP using TextFrame
import neattext.functions as nfx # Method 2: Using Functional Approach

# dir(nt)
# dir(nfx)
# ?nfx.clean_text

beforeNFX_data = data.copy()

data["Description"] = data["Description"].apply(lambda x: nfx.clean_text(x, puncts=True, special_char=True, contractions=True))
data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A   
1    536365 2010-12-01 08:26:00     71053   
2    536365 2010-12-01 08:26:00    84406B   
3    536365 2010-12-01 08:26:00    84029G   
4    536365 2010-12-01 08:26:00    84029E   

                           Description  Quantity  UnitPrice  Revenue  \
0    white hanging heart tlight holder         6       2.55    15.30   
1                  white metal lantern         6       3.39    20.34   
2       cream cupid hearts coat hanger         8       2.75    22.00   
3  knitted union flag hot water bottle         6       3.39    20.34   
4        red woolly hottie white heart         6       3.39    20.34   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17850  United Kingdom  
4       17850  United Kingdom

Let's verify!

In [414]:
cleanedDesc_NFX = beforeNFX_data["Description"].nunique() - data["Description"].nunique()
print(f"Number of cleaned Description using NFX: {cleanedDesc_NFX:,}")

Number of cleaned Description using NFX: 42


In [415]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (401604, 9)

No. of values in the dataset : 3,614,436
Total rows in the dataset : 401,604
Total columns in the dataset : 9

Total null values : 0
Total duplicated rows : 0

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 22,190
Total unique values for column InvoiceDate: 20,460
Total unique values for column StockCode: 3,684
Total unique values for column Description: 3,854
Total unique values for column Quantity: 436
Total unique values for column UnitPrice: 

After using NFX from NeatText Functions, we are able to clean 42 Descriptions and narrow down from 213 to 191 rows. <br>
Not bad, but not huge either.

For the sake of time saving, as this project is very time constraint, we will:

1. Combine all the words in one. <br>
For example, from:
```python
22199	frying pan red polkadot
22199	frying pan red retrospot
```
To:
```python
22129 frying pan red polkadot retrospot
```

2. Put necessary spaces. <br>
For example, from:
```python
20622 vippassport cover
```
To:
```python
20622 vip passport cover
```

3. Put space before and after a digit. <br>
For example, from:
```python
17107D	flower fairy5 drawer liners
```
To:
```python
17107D flower fairy 5 drawer liners
```

4. Delete unnecessary spaces before and after each sentence (only 1 space between words). <br>
For example, from:
```python
21175   gin tonic diet   metal sign   
```
To:
```python
21175 gin tonic diet metal sign
```

We will need to create a function that meets our requirements, and use:
- pandas library for data manipulation
- re library for regular expressions, which will help with string manipulation

Let me explain the function:

- It first combines all the descriptions per StockCode_fixed.
- It then creates a new DataFrame with the combined descriptions.
- The function then adds necessary spaces, for example changing 'vippassport cover' to 'vip passport cover'. <br>
It does this by adding a space between any lower-case letter followed by an upper-case letter.
- Then it adds a space before and after a digit.
- Lastly, it removes any unnecessary spaces in the description.

#### RegEx

In [416]:
import re
from collections import defaultdict

def process_data(df):
    # Combine all the words in one per StockCode
    combined = defaultdict(set) # use a set to avoid duplicates
    for _, row in df.iterrows():
        for word in row['Description'].split():
            combined[row['StockCode']].add(word)

    # Prepare new descriptions
    new_descriptions = {}
    for stock_code in combined.keys():
        description = " ".join(combined[stock_code])
        new_descriptions[stock_code] = description

    # Add necessary spaces
    for stock_code in new_descriptions.keys():
        new_descriptions[stock_code] = re.sub(r'(\w)([A-Z])', r'\1 \2', new_descriptions[stock_code])

    # Add space before and after a digit
    for stock_code in new_descriptions.keys():
        new_descriptions[stock_code] = re.sub(r'(\D)(\d)', r'\1 \2', new_descriptions[stock_code])
        new_descriptions[stock_code] = re.sub(r'(\d)(\D)', r'\1 \2', new_descriptions[stock_code])

    # Delete unnecessary spaces
    for stock_code in new_descriptions.keys():
        new_descriptions[stock_code] = ' '.join(new_descriptions[stock_code].split())

    # Update Description column in the original dataframe
    df['Description'] = df['StockCode'].map(new_descriptions)

    return df

beforeRegex_data = data.copy()

data = process_data(data)
data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A   
1    536365 2010-12-01 08:26:00     71053   
2    536365 2010-12-01 08:26:00    84406B   
3    536365 2010-12-01 08:26:00    84029G   
4    536365 2010-12-01 08:26:00    84029E   

                               Description  Quantity  UnitPrice  Revenue  \
0  tlight hanging heart holder cream white         6       2.55    15.30   
1             moroccan metal lantern white         6       3.39    20.34   
2           coat hearts cream cupid hanger         8       2.75    22.00   
3      union flag hot bottle water knitted         6       3.39    20.34   
4            red heart hottie woolly white         6       3.39    20.34   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17850  United Kingdom  
4       17850  United Kingdom

In [417]:
# Identify the StockCode that have multiple Description
StockCode_Description_counts = data.groupby('StockCode')['Description'].nunique()

# Filter the StockCode that have multiple Description
StockCode_with_multiple_Description = StockCode_Description_counts[StockCode_Description_counts > 1]

# Show
StockCode_with_multiple_Description.to_frame().reset_index()

Empty DataFrame
Columns: [StockCode, Description]
Index: []

In [418]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (401604, 9)

No. of values in the dataset : 3,614,436
Total rows in the dataset : 401,604
Total columns in the dataset : 9

Total null values : 0
Total duplicated rows : 2

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 22,190
Total unique values for column InvoiceDate: 20,460
Total unique values for column StockCode: 3,684
Total unique values for column Description: 3,647
Total unique values for column Quantity: 436
Total unique values for column UnitPrice: 

In [419]:
cleanedDesc_Regex = beforeRegex_data["Description"].nunique() - data["Description"].nunique()
cleanedDesc_Total = beforeNFX_data["Description"].nunique() - data["Description"].nunique()

print(f"Number of Description from the original data: {beforeNFX_data['Description'].nunique():,}")
print(f"Number of Description in our current data: {data['Description'].nunique():,}")

print(f"\nNumber of cleaned Description using NFX: {cleanedDesc_NFX:,}")
print(f"Number of cleaned Description after Regex: {cleanedDesc_Regex:,}")

print(f"\nNumber of Description fixed in total: {cleanedDesc_Total:,}")

Number of Description from the original data: 3,896
Number of Description in our current data: 3,647

Number of cleaned Description using NFX: 42
Number of cleaned Description after Regex: 207

Number of Description fixed in total: 249


As we see, we have reduced 6.4% of Descriptions. <br>
But the main issue still lies in our data..  _**StockCode still doesn't match the number of Description**_

So we'll take a look at StockCode now

### StockCode

In [420]:
# Identify the Description that have multiple StockCode
Description_StockCode_counts = data.groupby('Description')['StockCode'].nunique()

# Filter the Description that have multiple StockCode
Description_with_multiple_StockCode = Description_StockCode_counts[Description_StockCode_counts > 1]

# Show
Description_with_multiple_StockCode.to_frame().reset_index()

Description  StockCode
0           70 s retro plastic tray          2
1                base frosted white          2
2               bathroom sign metal          2
3        cake placemats 4 set fairy          2
4        candle rectangle columbian          2
5     candleholder glass flock pink          2
6     cherry cabinet square blossom          2
7   cherry flask decorative blossom          2
8     cover cake pink cushion fairy          2
9         cover sud rose cushion du          2
10            cube candle columbian          2
11  de nile jewelled photoframe eau          2
12                     door key fob          2
13       easter rabbit flowers pink          2
14      french cushion floral cover          2
15     french lattice cover cushion          2
16     french paisley cover cushion          2
17              holder tlight heart          2
18        jewelled frame photo pink          2
19     pencils colouring brown tube          2
20      ribs lampshade bamboo white          2
21            ring key bling letter          8
22           round candle columbian          3
23         served sign dinner metal          2
24    signcupcake single hook metal          3
25          sucker clock round blue          2
26               tidy office drawer          2
27         tray retro plastic daisy          2
28         tray retro plastic polka          2

In [421]:
# Filter the original dataset based on Description that have multiple StockCode
filtered_data = data[data['Description'].isin(Description_with_multiple_StockCode.index)]

# View all columns for Description that have multiple StockCode
filtered_data = filtered_data.groupby(['Description', 'StockCode', 'UnitPrice'])['Revenue'].sum().to_frame()

# Show
# pd.set_option("display.max_rows", None)
filtered_data.head(20)

Revenue
Description                   StockCode UnitPrice         
70 s retro plastic tray       79190A    0.42        141.54
                              79192A    1.25          3.75
base frosted white            79403     0.85         75.65
                              79406     0.22         30.80
bathroom sign metal           21171     1.25        300.00
                                        1.45        266.80
                              82580     0.42        450.24
                                        0.55       1866.15
                                        0.73        394.20
                                        0.74         71.04
                                        0.92         88.32
                                        1.25         20.00
cake placemats 4 set fairy    84509B    3.75        585.00
                              84509G    1.25        492.50
                                        3.75        363.75
candle rectangle columbian    72131     1.65        158.40
                                        1.95         78.00
                              72133     1.25         48.75
candleholder glass flock pink 79329     0.38          2.28
                                        1.65          9.90

There are 29 Description with multiple StockCode. <br>
Let's fix those by choosing only one primary `StockCode`, and change the rest to the selected main/primary `StockCode`. <br><br>

We'll stay careful though and rename the "original" `StockCode` to `StockCode_old` for reference, so we can verify if the process went well as we'd like to. <br><br>

What that meant is, to make sure we are not loosing any data or rows during the `drop_duplicates()` and `merge()`steps. <br>
In short, the number of rows from our orginal data should equal after the operation.

In [422]:
# Count number of rows before operation
print(f"Number of rows before operation: {len(data):,}")

# Create a DataFrame mapping of unique Descriptions to one StockCode
mapping = data.drop_duplicates('Description')[['StockCode', 'Description']]

# Merge the mapping onto the original data
data = data.merge(mapping, on='Description', suffixes=('_old', '_fixed'))

# Rename StockCode_fixed to StockCode
data = data.rename({"StockCode_fixed": "StockCode"}, axis=1)

# Rearrange data
data = data[["InvoiceNo", "InvoiceDate", "StockCode_old", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue", "CustomerID", "Country"]]

# Drop the old StockCode column
# data = data.drop(columns='StockCode_old')

# Count number of rows after operation
print(f"Number of rows after operation: {len(data):,}")

Number of rows before operation: 401,604
Number of rows after operation: 401,604


In [423]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (401604, 10)

No. of values in the dataset : 4,016,040
Total rows in the dataset : 401,604
Total columns in the dataset : 10

Total null values : 0
Total duplicated rows : 2

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 22,190
Total unique values for column InvoiceDate: 20,460
Total unique values for column StockCode_old: 3,684
Total unique values for column StockCode: 3,647
Total unique values for column Description: 3,647
Total unique values for column Qu

Yay! StockCode and Description are now aligned! <br>
We'll just have to get rid of the 2 duplicates and we can move on

In [424]:
data[data.duplicated(keep=False)]

InvoiceNo         InvoiceDate StockCode_old StockCode  \
340137    554084 2011-05-22 11:52:00         23298     23298   
340138    554084 2011-05-22 11:52:00         23298     23298   
343582    575335 2011-11-09 13:56:00         23203     23203   
343583    575335 2011-11-09 13:56:00         23203     23203   

                                    Description  Quantity  UnitPrice  Revenue  \
340137                           spotty bunting         3       4.95    14.85   
340138                           spotty bunting         3       4.95    14.85   
343582  patterns doily bag jumbo doiley vintage       300       1.79   537.00   
343583  patterns doily bag jumbo doiley vintage       300       1.79   537.00   

        CustomerID         Country  
340137       12909  United Kingdom  
340138       12909  United Kingdom  
343582       12931  United Kingdom  
343583       12931  United Kingdom

In [425]:
data = data.drop_duplicates()
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (401602, 10)

No. of values in the dataset : 4,016,020
Total rows in the dataset : 401,602
Total columns in the dataset : 10

Total null values : 0
Total duplicated rows : 0

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 22,190
Total unique values for column InvoiceDate: 20,460
Total unique values for column StockCode_old: 3,684
Total unique values for column StockCode: 3,647
Total unique values for column Description: 3,647
Total unique values for column Qu

Let's check whether there are other anomalies we can fix

In [426]:
data.describe(include='all')

InvoiceNo                    InvoiceDate StockCode_old StockCode  \
count     401602                         401602        401602    401602   
unique     22190                            NaN          3684      3647   
top       576339                            NaN        85123A    85123A   
freq         542                            NaN          2065      2065   
mean         NaN  2011-07-10 12:08:08.129839872           NaN       NaN   
min          NaN            2010-12-01 08:26:00           NaN       NaN   
25%          NaN            2011-04-06 15:02:00           NaN       NaN   
50%          NaN            2011-07-29 15:40:00           NaN       NaN   
75%          NaN            2011-10-20 11:58:00           NaN       NaN   
max          NaN            2011-12-09 12:50:00           NaN       NaN   
std          NaN                            NaN           NaN       NaN   

                                    Description  Quantity  UnitPrice  \
count                                    401602 401602.00  401602.00   
unique                                     3647       NaN        NaN   
top     tlight hanging heart holder cream white       NaN        NaN   
freq                                       2065       NaN        NaN   
mean                                        NaN     12.18       3.47   
min                                         NaN -80995.00       0.00   
25%                                         NaN      2.00       1.25   
50%                                         NaN      5.00       1.95   
75%                                         NaN     12.00       3.75   
max                                         NaN  80995.00   38970.00   
std                                         NaN    250.28      69.76   

          Revenue  CustomerID         Country  
count   401602.00   401602.00          401602  
unique        NaN         NaN              37  
top           NaN         NaN  United Kingdom  
freq          NaN         NaN          356726  
mean        20.61    15281.17             NaN  
min    -168469.60    12346.00             NaN  
25%          4.25    13939.00             NaN  
50%         11.70    15145.00             NaN  
75%         19.80    16784.00             NaN  
max     168469.60    18287.00             NaN  
std        430.35     1714.00             NaN

What did we find out:
- Quantity, UnitPrice, and Revenue have values of 0 going negative, which is unusual <br>
_It may be that these items were gifted to clients. Let's see later_

- Quantity has a maximum of 80,995 <br>
_This is also unsual, let's see what it's about later as well_

- There is a UnitPrice of 38,970.75 <br>
_We'll take a look on it_

- Revenue of 168,469 <br>
_We'll find out more on this_

In [427]:
profiler.uniqueColumns(data)

UNIQUE VALUES FOR EACH COLUMN :
-------------------------------------------------------------------------------------------------------------
UNIQUE VALUES for column 'InvoiceNo' : 22190 including NaN values, 22190 excluding Nan values

['536365' '536373' '536375' ... '579108' '581483' 'C581484']

-------------------------------------------------------------------------------------------------------------
UNIQUE VALUES for column 'InvoiceDate' : 20460 including NaN values, 20460 excluding Nan values

<DatetimeArray>
['2010-12-01 08:26:00', '2010-12-01 09:02:00', '2010-12-01 09:32:00',
 '2010-12-01 10:19:00', '2010-12-01 10:39:00', '2010-12-01 10:51:00',
 '2010-12-01 11:21:00', '2010-12-01 11:33:00', '2010-12-01 12:36:00',
 '2010-12-01 12:43:00',
 ...
 '2011-11-28 09:11:00', '2011-11-29 09:14:00', '2011-12-02 11:50:00',
 '2011-12-07 17:22:00', '2011-12-09 12:21:00', '2011-12-06 10:28:00',
 '2011-12-05 09:04:00', '2011-11-28 11:44:00', '2011-12-09 09:15:00',
 '2011-12-09 09:27:00']
Lengt

Other stuffs to take into account:
- perhaps renaming few countries for clearer information
    - EIRE to Ireland
    - RSA to replubic of South Africa
    - [European Community](https://en.wikipedia.org/wiki/European_Communities) to European Community (EEC, ECSC, and EAEC)

For reference:
- [EEC](https://en.wikipedia.org/wiki/European_Economic_Community)
    - European Economic Community
    - renamed the European Community (EC) in 1993 by the [Maastricht Treaty](https://en.wikipedia.org/wiki/Maastricht_Treaty) establishing the [European Union](https://en.wikipedia.org/wiki/European_Union)
- [ECSC](https://en.wikipedia.org/wiki/European_Coal_and_Steel_Community)
    - European Coal and Steel Community
- [EAEC or Euratom](https://en.wikipedia.org/wiki/European_Atomic_Energy_Community)
    - European Atomic Energy Community

In [428]:
data.sort_values(by="UnitPrice", ascending=False).head(25)

InvoiceNo         InvoiceDate StockCode_old StockCode Description  \
195929   C556445 2011-06-10 15:31:00             M         M      manual   
18602    C551685 2011-05-03 12:51:00          POST      POST     postage   
18603     551697 2011-05-03 13:46:00          POST      POST     postage   
195892   C551699 2011-05-03 14:12:00             M         M      manual   
195970   C560372 2011-07-18 12:26:00             M         M      manual   
196112    573077 2011-10-27 14:13:00             M         M      manual   
196114    573080 2011-10-27 14:20:00             M         M      manual   
196113   C573079 2011-10-27 14:15:00             M         M      manual   
196094   C571750 2011-10-19 11:16:00             M         M      manual   
196096    571751 2011-10-19 11:18:00             M         M      manual   
196058    569382 2011-10-03 16:44:00             M         M      manual   
196006   C562647 2011-08-08 12:56:00             M         M      manual   
195984   C560647 2011-07-20 11:31:00             M         M      manual   
196012    562946 2011-08-11 09:38:00             M         M      manual   
195860   C548830 2011-04-04 13:08:00             M         M      manual   
195855    548813 2011-04-04 13:03:00             M         M      manual   
196095   C571750 2011-10-19 11:16:00             M         M      manual   
196097    571751 2011-10-19 11:18:00             M         M      manual   
195863   C548834 2011-04-04 13:09:00             M         M      manual   
195858    548820 2011-04-04 13:04:00             M         M      manual   
196029    566927 2011-09-15 15:20:00             M         M      manual   
44402    C549452 2011-04-08 14:17:00             D         D    discount   
195868    549468 2011-04-08 14:27:00             M         M      manual   
196028   C566925 2011-09-15 15:18:00             M         M      manual   
195774   C542348 2011-01-27 12:09:00             M         M      manual   

        Quantity  UnitPrice   Revenue  CustomerID         Country  
195929        -1   38970.00 -38970.00       15098  United Kingdom  
18602         -1    8142.75  -8142.75       16029  United Kingdom  
18603          1    8142.75   8142.75       16029  United Kingdom  
195892        -1    6930.00  -6930.00       16029  United Kingdom  
195970        -1    4287.63  -4287.63       17448  United Kingdom  
196112         1    4161.06   4161.06       12536          France  
196114         1    4161.06   4161.06       12536          France  
196113        -2    4161.06  -8322.12       12536          France  
196094        -1    3949.32  -3949.32       12744       Singapore  
196096         1    3949.32   3949.32       12744       Singapore  
196058         1    3155.95   3155.95       15502  United Kingdom  
196006        -1    3155.95  -3155.95       15502  United Kingdom  
195984        -1    3060.60  -3060.60       18102  United Kingdom  
196012         1    2500.00   2500.00       15581  United Kingdom  
195860        -1    2382.92  -2382.92       12744       Singapore  
195855         1    2382.92   2382.92       12744       Singapore  
196095        -1    2118.74  -2118.74       12744       Singapore  
196097         1    2118.74   2118.74       12744       Singapore  
195863        -1    2053.07  -2053.07       12744       Singapore  
195858         1    2053.07   2053.07       12744       Singapore  
196029         1    2033.10   2033.10       17846  United Kingdom  
44402         -1    1867.86  -1867.86       17940  United Kingdom  
195868         1    1867.86   1867.86       17940  United Kingdom  
196028        -1    1829.84  -1829.84       12748  United Kingdom  
195774        -1    1715.85  -1715.85       12539           Spain

We notice only character values in the StockCode column, <br>
which is different from the usual alpahnumeric. <br><br>
Let's take a closer look on those

In [429]:
# Filter only character values from StockCode
alphaStockCode = data[data['StockCode'].str.isalpha()]

# Count unique values from the specified columns
unique_counts = {
    "StockCode_old": alphaStockCode["StockCode_old"].nunique(),
    "StockCode": alphaStockCode["StockCode"].nunique(),
    "Description": alphaStockCode["Description"].nunique()
}

# Get unique values from the specified columns
unique_values = {
    "StockCode_old": alphaStockCode["StockCode_old"].unique(),
    "StockCode": alphaStockCode["StockCode"].unique(),
    "Description": alphaStockCode["Description"].unique()
}

# Print count of unique values
for column, count in unique_counts.items():
    print(f"Number of unique values in column {column}: {count}")

print()

# Print unique values
for column, values in unique_values.items():
    print(f"Unique values in column {column}: {values}")

Number of unique values in column StockCode_old: 6
Number of unique values in column StockCode: 6
Number of unique values in column Description: 6

Unique values in column StockCode_old: ['POST' 'D' 'M' 'PADS' 'DOT' 'CRUK']
Unique values in column StockCode: ['POST' 'D' 'M' 'PADS' 'DOT' 'CRUK']
Unique values in column Description: ['postage' 'discount' 'manual' 'pads cushions match' 'dotcom postage'
 'cruk commission']


In [430]:
alphaStockCode.groupby(["StockCode", "Description"])[["Quantity", "Revenue"]].sum().reset_index().sort_values(by="Revenue")

StockCode          Description  Quantity   Revenue
3         M               manual      2944 -58745.46
0      CRUK      cruk commission       -16  -7933.43
1         D             discount     -1194  -5696.22
4      PADS  pads cushions match         4      0.00
2       DOT       dotcom postage        16  11906.36
5      POST              postage      3002  66710.24

In [431]:
backup.loc[backup["StockCode"] == "PADS"]

InvoiceNo      InvoiceDate StockCode                 Description  \
157195    550193   4/15/2011 9:27      PADS  PADS TO MATCH ALL CUSHIONS   
279045    561226  7/26/2011 10:13      PADS  PADS TO MATCH ALL CUSHIONS   
358655    568158  9/25/2011 12:22      PADS  PADS TO MATCH ALL CUSHIONS   
359871    568200  9/25/2011 14:58      PADS  PADS TO MATCH ALL CUSHIONS   

        Quantity  UnitPrice  CustomerID         Country  
157195         1       0.00    13952.00  United Kingdom  
279045         1       0.00    15618.00  United Kingdom  
358655         1       0.00    16133.00  United Kingdom  
359871         1       0.00    16198.00  United Kingdom

In [432]:
labels = ["M", "CRUK", "D", "DOT", "POST"]
description = ["manual", "commission cruk", "discount", "dotcom postage", "postage"]

for label, desc in zip(labels, description):
    print(f"{label}: {desc}")
    display(alphaStockCode[alphaStockCode["StockCode"] == label][["UnitPrice"]].describe().reset_index())
    print("-" * 20)

M: manual


index  UnitPrice
0  count     460.00
1   mean     338.04
2    std    1945.27
3    min       0.00
4    25%       0.85
5    50%       3.25
6    75%     110.92
7    max   38970.00

--------------------
CRUK: commission cruk


index  UnitPrice
0  count      16.00
1   mean     495.84
2    std     364.16
3    min       1.60
4    25%     284.25
5    50%     471.77
6    75%     668.98
7    max    1100.44

--------------------
D: discount


index  UnitPrice
0  count      77.00
1   mean      72.48
2    std     219.27
3    min       0.01
4    25%      13.88
5    50%      22.97
6    75%      57.60
7    max    1867.86

--------------------
DOT: dotcom postage


index  UnitPrice
0  count      16.00
1   mean     744.15
2    std     540.83
3    min      11.17
4    25%     389.08
5    50%     715.85
6    75%     998.63
7    max    1599.26

--------------------
POST: postage


index  UnitPrice
0  count    1196.00
1   mean      37.89
2    std     334.12
3    min       1.00
4    25%      18.00
5    50%      18.00
6    75%      18.00
7    max    8142.75

--------------------


- The Description labeled as 'Manual' is quite vague. <br>
Considering the lack of specific information about the company's operations, my assumption is that 'Manual' refers to services provided in conjunction with the purchase of other items. <br>
However, there are significant irregularities in these transactions that do not directly relate to individual product sales. <br>
Therefore, we will remove records associated with 'Manual' as well. <br><br>

- The label 'CRUK Commission' suggests a payment made to an external organization, and a quick search revealed its association with Cancer Research UK. This payment may be part of an initiative to contribute proceeds to cancer research. <br>
Since it is not directly related to sales, we should exclude rows with 'CRUK Commission' from our analysis. <br><br>

- It seems quite obvious that the category 'Discount' refers to the discounts offered for the sold products. <br>
This is supported by the fact that all these transactions have negative sales quantities. <br>
Since discounts directly affect the product prices and have a direct impact on sales, it is reasonable to keep the 'Discount' category in the dataframe. <br><br>

- As for 'CUSHION MATCH PADS', it's just a normal product the shop is selling, so we won't eliminate this label. <br><br>

- It appears that the label 'DOTCOM POSTAGE' indicates the amount customers spent on postage. <br><br>

- Additionally, including postage in the analysis might distort the amount spent by different groups of customers. <br>
We will also remove another similar label, 'POSTAGE'. <br><br>

In [433]:
labels = ["M", "CRUK", "DOT", "POST"]

allStockCode_data = data.copy()

print(f"StockCode unique values before the process: {data['StockCode'].nunique():,}")
print(f"Number of unique values to eliminate: {len(labels):,}")

data = data.loc[~data["StockCode"].isin(labels)]

print(f"StockCode unique values after the process: {data['StockCode'].nunique():,}")

StockCode unique values before the process: 3,647
Number of unique values to eliminate: 4
StockCode unique values after the process: 3,643


Let's actually not forget to drop the StockCode_old column since we don't really need it anymore

In [434]:
with_oldStockCode = data.copy()
data = data.drop("StockCode_old", axis=1)
data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A   
1    536373 2010-12-01 09:02:00    85123A   
2    536375 2010-12-01 09:32:00    85123A   
3    536390 2010-12-01 10:19:00    85123A   
4    536394 2010-12-01 10:39:00    85123A   

                               Description  Quantity  UnitPrice  Revenue  \
0  tlight hanging heart holder cream white         6       2.55    15.30   
1  tlight hanging heart holder cream white         6       2.55    15.30   
2  tlight hanging heart holder cream white         6       2.55    15.30   
3  tlight hanging heart holder cream white        64       2.55   163.20   
4  tlight hanging heart holder cream white        32       2.55    81.60   

   CustomerID         Country  
0       17850  United Kingdom  
1       17850  United Kingdom  
2       17850  United Kingdom  
3       17511  United Kingdom  
4       13408  United Kingdom

PERFECT! Time to work on the countries

## Country

This was what we have decided earlier:
- rename countries for clearer information
    - EIRE to Ireland
    - RSA to replubic of South Africa
    - [European Community](https://en.wikipedia.org/wiki/European_Communities) to European Community (EEC, ECSC, and EAEC)

For reference:
- [EEC](https://en.wikipedia.org/wiki/European_Economic_Community)
    - European Economic Community
    - renamed the European Community (EC) in 1993 by the [Maastricht Treaty](https://en.wikipedia.org/wiki/Maastricht_Treaty) establishing the [European Union](https://en.wikipedia.org/wiki/European_Union)
- [ECSC](https://en.wikipedia.org/wiki/European_Coal_and_Steel_Community)
    - European Coal and Steel Community
- [EAEC or Euratom](https://en.wikipedia.org/wiki/European_Atomic_Energy_Community)
    - European Atomic Energy Community

Time to update them!

In [435]:
data.loc[data["Country"] == "EIRE", "Country"] = "Ireland"
data.loc[data["Country"] == "RSA", "Country"] = "Republic of South Africa"
data.loc[data["Country"] == "European Community", "Country"] = "European Community (EEC, ECSC, and EAEC)"

# Verify
sorted(data["Country"].unique())

['Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'European Community (EEC, ECSC, and EAEC)',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Iceland',
 'Ireland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'Republic of South Africa',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified']

There is a customer with 2 countries. <br>
This client changed country from Switzerland to Cyprus 5 days after its last purchase.. <br>
We may have to do something about it, specially when transferring subset to SQL

In [436]:
data[data["CustomerID"] == 12457].sort_values(by="InvoiceDate")

InvoiceNo         InvoiceDate StockCode  \
7179      550188 2011-04-14 18:57:00     22623   
281548    550188 2011-04-14 18:57:00    47594A   
316748    550188 2011-04-14 18:57:00    84086C   
258379    550188 2011-04-14 18:57:00     47566   
244288    550188 2011-04-14 18:57:00     22636   
...          ...                 ...       ...   
390747    566756 2011-09-14 15:54:00     23388   
43276     567188 2011-09-19 09:04:00    15056N   
43292     569489 2011-10-04 13:13:00    15056N   
43293    C569490 2011-10-04 13:15:00    15056N   
362512   C570835 2011-10-12 13:46:00     23236   

                                     Description  Quantity  UnitPrice  \
7179                   box jigsaw blocks vintage         3       4.95   
281548                   washbag carousel design         6       1.95   
316748                    pinkpurple retro radio        12       2.95   
258379                             party bunting         8       4.95   
244288        parade circus childs breakfast set         1       0.00   
...                                          ...       ...        ...   
390747           woodland backpack mini rucksack         8       4.15   
43276                  parasol edwardian natural        33       5.95   
43292                  parasol edwardian natural        33       5.95   
43293                  parasol edwardian natural       -33       5.95   
362512  tin doily biscuit storage doiley vintage        -5       2.89   

        Revenue  CustomerID      Country  
7179      14.85       12457  Switzerland  
281548    11.70       12457  Switzerland  
316748    35.40       12457  Switzerland  
258379    39.60       12457  Switzerland  
244288     0.00       12457  Switzerland  
...         ...         ...          ...  
390747    33.20       12457  Switzerland  
43276    196.35       12457       Cyprus  
43292    196.35       12457       Cyprus  
43293   -196.35       12457       Cyprus  
362512   -14.45       12457  Switzerland  

[65 rows x 9 columns]

In [437]:
data.loc[data["CustomerID"] == 12457, "Country"] = "Switzerland"

## Augement data with dates

In [438]:
data["invoiceDate_norm"] = data["InvoiceDate"].dt.normalize()       # keeps dtype as datetime64[ns]
data["Year"] = data["invoiceDate_norm"].dt.year                     # extracts year
data["YearMonth"] = data["invoiceDate_norm"].dt.strftime("%Y-%m")   # Year-Month
data["Month"] = data["invoiceDate_norm"].dt.month                   # returns the month as a number from 1 through 12
data["MonthDate"] = data["invoiceDate_norm"].dt.strftime("%m-%d")   # Month-Day
data["DayofMonth"] = data["invoiceDate_norm"].dt.day                # returns the number of days into the month the day is
data["Hour"] = data["InvoiceDate"].dt.hour                          # extracts hour
data["DayofWeek"] = data["invoiceDate_norm"].dt.weekday             # returns the weekday number starting at 0 for Mondays
data["Month_name"] = data["invoiceDate_norm"].dt.month_name()       # returns the locale’s named month, allowing you to pass in a different locale
data["Day_name"] = data["invoiceDate_norm"].dt.day_name()           # returns the name of the day based a given locale
# data["invoiceDay_year"] = data["invoiceDate_norm"].dt.dayofyear   # returns the number of days into the year the day is

data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A   
1    536373 2010-12-01 09:02:00    85123A   
2    536375 2010-12-01 09:32:00    85123A   
3    536390 2010-12-01 10:19:00    85123A   
4    536394 2010-12-01 10:39:00    85123A   

                               Description  Quantity  UnitPrice  Revenue  \
0  tlight hanging heart holder cream white         6       2.55    15.30   
1  tlight hanging heart holder cream white         6       2.55    15.30   
2  tlight hanging heart holder cream white         6       2.55    15.30   
3  tlight hanging heart holder cream white        64       2.55   163.20   
4  tlight hanging heart holder cream white        32       2.55    81.60   

   CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
0       17850  United Kingdom       2010-12-01  2010   2010-12     12   
1       17850  United Kingdom       2010-12-01  2010   2010-12     12   
2       17850  United Kingdom       2010-12-01  2010   2010-12     12   
3       17511  United Kingdom       2010-12-01  2010   2010-12     12   
4       13408  United Kingdom       2010-12-01  2010   2010-12     12   

  MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
0     12-01           1     8          2   December  Wednesday  
1     12-01           1     9          2   December  Wednesday  
2     12-01           1     9          2   December  Wednesday  
3     12-01           1    10          2   December  Wednesday  
4     12-01           1    10          2   December  Wednesday

Good. <br>
We have one more problem though.. <br><br>

I just found out we have unseen duplicated values in our data. <br>
The only thing that differenciated (_which made the duplicates hidden_) is the Quantity field. <br>
Let me show you:

## Quantity

In [439]:
subset_data = data.duplicated(subset=["InvoiceNo", "InvoiceDate", "StockCode", "Description", "UnitPrice"], keep=False)
dups = data[subset_data]
dups

InvoiceNo         InvoiceDate StockCode  \
42        537051 2010-12-05 11:12:00    85123A   
43        537051 2010-12-05 11:12:00    85123A   
44        537054 2010-12-05 11:40:00    85123A   
45        537054 2010-12-05 11:40:00    85123A   
83        537769 2010-12-08 12:17:00    85123A   
...          ...                 ...       ...   
401473    578936 2011-11-27 13:00:00     23575   
401481    580137 2011-12-01 19:54:00     23575   
401482    580137 2011-12-01 19:54:00     23575   
401532    580884 2011-12-06 12:21:00     23576   
401533    580884 2011-12-06 12:21:00     23576   

                                    Description  Quantity  UnitPrice  Revenue  \
42      tlight hanging heart holder cream white         3       2.95     8.85   
43      tlight hanging heart holder cream white         2       2.95     5.90   
44      tlight hanging heart holder cream white         2       2.95     5.90   
45      tlight hanging heart holder cream white         1       2.95     2.95   
83      tlight hanging heart holder cream white         1       2.95     2.95   
...                                         ...       ...        ...      ...   
401473                  paisley tray park snack         1       1.95     1.95   
401481                  paisley tray park snack         8       1.95    15.60   
401482                  paisley tray park snack         2       1.95     3.90   
401532             snack red tray doily vintage         1       1.95     1.95   
401533             snack red tray doily vintage         2       1.95     3.90   

        CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
42           15708  United Kingdom       2010-12-05  2010   2010-12     12   
43           15708  United Kingdom       2010-12-05  2010   2010-12     12   
44           16931  United Kingdom       2010-12-05  2010   2010-12     12   
45           16931  United Kingdom       2010-12-05  2010   2010-12     12   
83           15021  United Kingdom       2010-12-08  2010   2010-12     12   
...            ...             ...              ...   ...       ...    ...   
401473       16923  United Kingdom       2011-11-27  2011   2011-11     11   
401481       17566  United Kingdom       2011-12-01  2011   2011-12     12   
401482       17566  United Kingdom       2011-12-01  2011   2011-12     12   
401532       15907  United Kingdom       2011-12-06  2011   2011-12     12   
401533       15907  United Kingdom       2011-12-06  2011   2011-12     12   

       MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
42         12-05           5    11          6   December     Sunday  
43         12-05           5    11          6   December     Sunday  
44         12-05           5    11          6   December     Sunday  
45         12-05           5    11          6   December     Sunday  
83         12-08           8    12          2   December  Wednesday  
...          ...         ...   ...        ...        ...        ...  
401473     11-27          27    13          6   November     Sunday  
401481     12-01           1    19          3   December   Thursday  
401482     12-01           1    19          3   December   Thursday  
401532     12-06           6    12          1   December    Tuesday  
401533     12-06           6    12          1   December    Tuesday  

[9819 rows x 19 columns]

As we see, everything is the same besides the Quantity. <br>
Therefore, we have to combine these similar fields by aggregating the Quantity column. <br><br>

In [440]:
# Create aggregation on Quantity and Revenue to see what it looks like fixed
aggs = data.groupby(["InvoiceNo", "InvoiceDate", "StockCode", "Description", "UnitPrice", "CustomerID", "Country", "invoiceDate_norm", "Year", "YearMonth", "Month", "MonthDate", "DayofMonth", "Hour", "DayofWeek", "Month_name", "Day_name"], as_index=False).agg({"Quantity": "sum", "Revenue": "sum"})
aggs = aggs[["InvoiceNo", "InvoiceDate", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue", "CustomerID", "Country", "invoiceDate_norm", "Year", "YearMonth", "Month", "MonthDate", "DayofMonth", "Hour", "DayofWeek", "Month_name", "Day_name"]]
aggs

InvoiceNo         InvoiceDate StockCode  \
0         536365 2010-12-01 08:26:00     21730   
1         536365 2010-12-01 08:26:00     22752   
2         536365 2010-12-01 08:26:00     71053   
3         536365 2010-12-01 08:26:00    84029E   
4         536365 2010-12-01 08:26:00    84029G   
...          ...                 ...       ...   
394906   C581490 2011-12-09 09:57:00     22178   
394907   C581490 2011-12-09 09:57:00     23144   
394908   C581568 2011-12-09 11:57:00     21258   
394909   C581569 2011-12-09 11:58:00     20979   
394910   C581569 2011-12-09 11:58:00     84978   

                                Description  Quantity  UnitPrice  Revenue  \
0          frosted tlight glass star holder         6       4.25    25.50   
1              nesting boxes babushka 7 set         2       7.65    15.30   
2              moroccan metal lantern white         6       3.39    20.34   
3             red heart hottie woolly white         6       3.39    20.34   
4       union flag hot bottle water knitted         6       3.39    20.34   
...                                     ...       ...        ...      ...   
394906       victorian hanging glass tlight       -12       1.95   -23.40   
394907       tlight stars small zinc holder       -11       0.83    -9.13   
394908           box victorian sewing large        -5      10.95   -54.75   
394909        tube red retrospot 36 pencils        -5       1.25    -6.25   
394910      tlight jar hanging heart holder        -1       1.25    -1.25   

        CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
0            17850  United Kingdom       2010-12-01  2010   2010-12     12   
1            17850  United Kingdom       2010-12-01  2010   2010-12     12   
2            17850  United Kingdom       2010-12-01  2010   2010-12     12   
3            17850  United Kingdom       2010-12-01  2010   2010-12     12   
4            17850  United Kingdom       2010-12-01  2010   2010-12     12   
...            ...             ...              ...   ...       ...    ...   
394906       14397  United Kingdom       2011-12-09  2011   2011-12     12   
394907       14397  United Kingdom       2011-12-09  2011   2011-12     12   
394908       15311  United Kingdom       2011-12-09  2011   2011-12     12   
394909       17315  United Kingdom       2011-12-09  2011   2011-12     12   
394910       17315  United Kingdom       2011-12-09  2011   2011-12     12   

       MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
0          12-01           1     8          2   December  Wednesday  
1          12-01           1     8          2   December  Wednesday  
2          12-01           1     8          2   December  Wednesday  
3          12-01           1     8          2   December  Wednesday  
4          12-01           1     8          2   December  Wednesday  
...          ...         ...   ...        ...        ...        ...  
394906     12-09           9     9          4   December     Friday  
394907     12-09           9     9          4   December     Friday  
394908     12-09           9    11          4   December     Friday  
394909     12-09           9    11          4   December     Friday  
394910     12-09           9    11          4   December     Friday  

[394911 rows x 19 columns]

We can't see anything yet, that's why it was hard to detect at first sight cause it's "hidden" or "unseen". <br>
Let's take a random InvoiceNo and compare the before and after aggregation

In [441]:
# Before aggregation
sample = dups.loc[dups["InvoiceNo"] == "537051"].sort_values(by="StockCode")
sample

InvoiceNo         InvoiceDate StockCode  \
128533    537051 2010-12-05 11:12:00     21916   
128534    537051 2010-12-05 11:12:00     21916   
199913    537051 2010-12-05 11:12:00     22725   
199914    537051 2010-12-05 11:12:00     22725   
12489     537051 2010-12-05 11:12:00     22726   
12490     537051 2010-12-05 11:12:00     22726   
11569     537051 2010-12-05 11:12:00     22727   
11570     537051 2010-12-05 11:12:00     22727   
74493     537051 2010-12-05 11:12:00     22729   
74494     537051 2010-12-05 11:12:00     22729   
42        537051 2010-12-05 11:12:00    85123A   
43        537051 2010-12-05 11:12:00    85123A   

                                    Description  Quantity  UnitPrice  Revenue  \
128533          retro 12 sticks chalk set white         1       0.42     0.42   
128534          retro 12 sticks chalk set white         4       0.42     1.68   
199913           bakelike clock chocolate alarm         1       3.75     3.75   
199914           bakelike clock chocolate alarm         2       3.75     7.50   
12489                green bakelike clock alarm         2       3.75     7.50   
12490                green bakelike clock alarm         1       3.75     3.75   
11569                  red bakelike clock alarm         2       3.75     7.50   
11570                  red bakelike clock alarm         1       3.75     3.75   
74493               orange bakelike clock alarm         2       3.75     7.50   
74494               orange bakelike clock alarm         1       3.75     3.75   
42      tlight hanging heart holder cream white         3       2.95     8.85   
43      tlight hanging heart holder cream white         2       2.95     5.90   

        CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
128533       15708  United Kingdom       2010-12-05  2010   2010-12     12   
128534       15708  United Kingdom       2010-12-05  2010   2010-12     12   
199913       15708  United Kingdom       2010-12-05  2010   2010-12     12   
199914       15708  United Kingdom       2010-12-05  2010   2010-12     12   
12489        15708  United Kingdom       2010-12-05  2010   2010-12     12   
12490        15708  United Kingdom       2010-12-05  2010   2010-12     12   
11569        15708  United Kingdom       2010-12-05  2010   2010-12     12   
11570        15708  United Kingdom       2010-12-05  2010   2010-12     12   
74493        15708  United Kingdom       2010-12-05  2010   2010-12     12   
74494        15708  United Kingdom       2010-12-05  2010   2010-12     12   
42           15708  United Kingdom       2010-12-05  2010   2010-12     12   
43           15708  United Kingdom       2010-12-05  2010   2010-12     12   

       MonthDate  DayofMonth  Hour  DayofWeek Month_name Day_name  
128533     12-05           5    11          6   December   Sunday  
128534     12-05           5    11          6   December   Sunday  
199913     12-05           5    11          6   December   Sunday  
199914     12-05           5    11          6   December   Sunday  
12489      12-05           5    11          6   December   Sunday  
12490      12-05           5    11          6   December   Sunday  
11569      12-05           5    11          6   December   Sunday  
11570      12-05           5    11          6   December   Sunday  
74493      12-05           5    11          6   December   Sunday  
74494      12-05           5    11          6   December   Sunday  
42         12-05           5    11          6   December   Sunday  
43         12-05           5    11          6   December   Sunday

In [442]:
# After aggregation
aggs.loc[(aggs["InvoiceNo"] == "537051") & (aggs["StockCode"].isin(sample["StockCode"].unique()))].sort_values(by="StockCode")

InvoiceNo         InvoiceDate StockCode  \
5119    537051 2010-12-05 11:12:00     21916   
5133    537051 2010-12-05 11:12:00     22725   
5134    537051 2010-12-05 11:12:00     22726   
5135    537051 2010-12-05 11:12:00     22727   
5136    537051 2010-12-05 11:12:00     22729   
5145    537051 2010-12-05 11:12:00    85123A   

                                  Description  Quantity  UnitPrice  Revenue  \
5119          retro 12 sticks chalk set white         5       0.42     2.10   
5133           bakelike clock chocolate alarm         3       3.75    11.25   
5134               green bakelike clock alarm         3       3.75    11.25   
5135                 red bakelike clock alarm         3       3.75    11.25   
5136              orange bakelike clock alarm         3       3.75    11.25   
5145  tlight hanging heart holder cream white         5       2.95    14.75   

      CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
5119       15708  United Kingdom       2010-12-05  2010   2010-12     12   
5133       15708  United Kingdom       2010-12-05  2010   2010-12     12   
5134       15708  United Kingdom       2010-12-05  2010   2010-12     12   
5135       15708  United Kingdom       2010-12-05  2010   2010-12     12   
5136       15708  United Kingdom       2010-12-05  2010   2010-12     12   
5145       15708  United Kingdom       2010-12-05  2010   2010-12     12   

     MonthDate  DayofMonth  Hour  DayofWeek Month_name Day_name  
5119     12-05           5    11          6   December   Sunday  
5133     12-05           5    11          6   December   Sunday  
5134     12-05           5    11          6   December   Sunday  
5135     12-05           5    11          6   December   Sunday  
5136     12-05           5    11          6   December   Sunday  
5145     12-05           5    11          6   December   Sunday

Eactly what we wanted!
Now, let's apply aggregation to our main data

In [443]:
beforeAggregation_Quantity = data.copy()

data = data.groupby(["InvoiceNo", "InvoiceDate", "StockCode", "Description", "UnitPrice", "CustomerID", "Country", "invoiceDate_norm", "Year", "YearMonth", "Month", "MonthDate", "DayofMonth", "Hour", "DayofWeek", "Month_name", "Day_name"], as_index=False).agg({"Quantity": "sum", "Revenue": "sum"})
data = data[["InvoiceNo", "InvoiceDate", "StockCode", "Description", "Quantity", "UnitPrice", "Revenue", "CustomerID", "Country", "invoiceDate_norm", "Year", "YearMonth", "Month", "MonthDate", "DayofMonth", "Hour", "DayofWeek", "Month_name", "Day_name"]]
data.head()

InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00     21730   
1    536365 2010-12-01 08:26:00     22752   
2    536365 2010-12-01 08:26:00     71053   
3    536365 2010-12-01 08:26:00    84029E   
4    536365 2010-12-01 08:26:00    84029G   

                           Description  Quantity  UnitPrice  Revenue  \
0     frosted tlight glass star holder         6       4.25    25.50   
1         nesting boxes babushka 7 set         2       7.65    15.30   
2         moroccan metal lantern white         6       3.39    20.34   
3        red heart hottie woolly white         6       3.39    20.34   
4  union flag hot bottle water knitted         6       3.39    20.34   

   CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
0       17850  United Kingdom       2010-12-01  2010   2010-12     12   
1       17850  United Kingdom       2010-12-01  2010   2010-12     12   
2       17850  United Kingdom       2010-12-01  2010   2010-12     12   
3       17850  United Kingdom       2010-12-01  2010   2010-12     12   
4       17850  United Kingdom       2010-12-01  2010   2010-12     12   

  MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
0     12-01           1     8          2   December  Wednesday  
1     12-01           1     8          2   December  Wednesday  
2     12-01           1     8          2   December  Wednesday  
3     12-01           1     8          2   December  Wednesday  
4     12-01           1     8          2   December  Wednesday

In [444]:
profiler.moreInfo(data)

MORE DATA INFO :
-------------------------------------------------------------------------------------------------------------
Data shape : (394911, 19)

No. of values in the dataset : 7,503,309
Total rows in the dataset : 394,911
Total columns in the dataset : 19

Total null values : 0
Total duplicated rows : 0

RATIO OF MISSING AND DUPLICATED VALUES IN OUR DATA :
-------------------------------------------------------------------------------------------------------------

Percentage of null values in the data : 0.0%
Percentage of duplicates in the data : 0.0%


NUMBER OF UNIQUE VALUES PER COLUMN :
-------------------------------------------------------------------------------------------------------------
Total unique values for column InvoiceNo: 21,867
Total unique values for column InvoiceDate: 20,203
Total unique values for column StockCode: 3,643
Total unique values for column Description: 3,643
Total unique values for column Quantity: 433
Total unique values for column UnitPrice

## Returns dataset

In [445]:
returns = data[data["Quantity"] <= 0].copy()

print(f"Number of rows with returned items: {len(data):,}")
print(f"Number of returned items: {len(returns):,}")

data = data[data["Quantity"] >= 0].copy()

# convert InvoiceNo to int64 from our current dataset
data["InvoiceNo"] = data["InvoiceNo"].astype(int)

print(f"Number of rows after removing returned items: {len(data):,}")

Number of rows with returned items: 394,911
Number of returned items: 8,551
Number of rows after removing returned items: 386,360


In [446]:
returns.head()

InvoiceNo         InvoiceDate StockCode                    Description  \
386360   C536379 2010-12-01 09:41:00         D                       discount   
386361   C536383 2010-12-01 09:49:00    35004C    3 coloured flying ducks set   
386362   C536391 2010-12-01 10:24:00     21484    hot grey bottle water chick   
386363   C536391 2010-12-01 10:24:00     21980  12 red pack retrospot tissues   
386364   C536391 2010-12-01 10:24:00     21983   12 paisley pack blue tissues   

        Quantity  UnitPrice  Revenue  CustomerID         Country  \
386360        -1      27.50   -27.50       14527  United Kingdom   
386361        -1       4.65    -4.65       15311  United Kingdom   
386362       -12       3.45   -41.40       17548  United Kingdom   
386363       -24       0.29    -6.96       17548  United Kingdom   
386364       -24       0.29    -6.96       17548  United Kingdom   

       invoiceDate_norm  Year YearMonth  Month MonthDate  DayofMonth  Hour  \
386360       2010-12-01  2010   2010-12     12     12-01           1     9   
386361       2010-12-01  2010   2010-12     12     12-01           1     9   
386362       2010-12-01  2010   2010-12     12     12-01           1    10   
386363       2010-12-01  2010   2010-12     12     12-01           1    10   
386364       2010-12-01  2010   2010-12     12     12-01           1    10   

        DayofWeek Month_name   Day_name  
386360          2   December  Wednesday  
386361          2   December  Wednesday  
386362          2   December  Wednesday  
386363          2   December  Wednesday  
386364          2   December  Wednesday

Let's just ensure everything is fine until here

In [447]:
data.dtypes

InvoiceNo                    int64
InvoiceDate         datetime64[ns]
StockCode                   object
Description                 object
Quantity                     int64
UnitPrice                  float64
Revenue                    float64
CustomerID                   int64
Country                     object
invoiceDate_norm    datetime64[ns]
Year                         int32
YearMonth                   object
Month                        int32
MonthDate                   object
DayofMonth                   int32
Hour                         int32
DayofWeek                    int32
Month_name                  object
Day_name                    object
dtype: object

# Export data for MySQL
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Prepare data and subsets

In [448]:
data.head()

InvoiceNo         InvoiceDate StockCode  \
0     536365 2010-12-01 08:26:00     21730   
1     536365 2010-12-01 08:26:00     22752   
2     536365 2010-12-01 08:26:00     71053   
3     536365 2010-12-01 08:26:00    84029E   
4     536365 2010-12-01 08:26:00    84029G   

                           Description  Quantity  UnitPrice  Revenue  \
0     frosted tlight glass star holder         6       4.25    25.50   
1         nesting boxes babushka 7 set         2       7.65    15.30   
2         moroccan metal lantern white         6       3.39    20.34   
3        red heart hottie woolly white         6       3.39    20.34   
4  union flag hot bottle water knitted         6       3.39    20.34   

   CustomerID         Country invoiceDate_norm  Year YearMonth  Month  \
0       17850  United Kingdom       2010-12-01  2010   2010-12     12   
1       17850  United Kingdom       2010-12-01  2010   2010-12     12   
2       17850  United Kingdom       2010-12-01  2010   2010-12     12   
3       17850  United Kingdom       2010-12-01  2010   2010-12     12   
4       17850  United Kingdom       2010-12-01  2010   2010-12     12   

  MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
0     12-01           1     8          2   December  Wednesday  
1     12-01           1     8          2   December  Wednesday  
2     12-01           1     8          2   December  Wednesday  
3     12-01           1     8          2   December  Wednesday  
4     12-01           1     8          2   December  Wednesday

In [449]:
returns.head()

InvoiceNo         InvoiceDate StockCode                    Description  \
386360   C536379 2010-12-01 09:41:00         D                       discount   
386361   C536383 2010-12-01 09:49:00    35004C    3 coloured flying ducks set   
386362   C536391 2010-12-01 10:24:00     21484    hot grey bottle water chick   
386363   C536391 2010-12-01 10:24:00     21980  12 red pack retrospot tissues   
386364   C536391 2010-12-01 10:24:00     21983   12 paisley pack blue tissues   

        Quantity  UnitPrice  Revenue  CustomerID         Country  \
386360        -1      27.50   -27.50       14527  United Kingdom   
386361        -1       4.65    -4.65       15311  United Kingdom   
386362       -12       3.45   -41.40       17548  United Kingdom   
386363       -24       0.29    -6.96       17548  United Kingdom   
386364       -24       0.29    -6.96       17548  United Kingdom   

       invoiceDate_norm  Year YearMonth  Month MonthDate  DayofMonth  Hour  \
386360       2010-12-01  2010   2010-12     12     12-01           1     9   
386361       2010-12-01  2010   2010-12     12     12-01           1     9   
386362       2010-12-01  2010   2010-12     12     12-01           1    10   
386363       2010-12-01  2010   2010-12     12     12-01           1    10   
386364       2010-12-01  2010   2010-12     12     12-01           1    10   

        DayofWeek Month_name   Day_name  
386360          2   December  Wednesday  
386361          2   December  Wednesday  
386362          2   December  Wednesday  
386363          2   December  Wednesday  
386364          2   December  Wednesday

We can divide our main dataset into four tables:
- Customer information
- Invoice information
- Product information
- Sales information

Here's a way to structure our tables, along with suggested primary and foreign keys:

1. Customer Information:
   - client_id (Primary Key)
   - CustomerID 
   - Country

2. Product Information:
   - product_id (Primary Key)
   - StockCode 
   - UnitPrice
   - Description

3. Invoice Information:
   - invoice_id (Primary Key)
   - InvoiceNo
   - InvoiceDate
   - invoiceDate_norm
   - Year
   - YearMonth
   - Month
   - MonthDate
   - DayofMonth
   - Hour
   - DayofWeek
   - Month_name
   - Day_name

4. Sales Information:
   - invoice_id (Foreign Key: links to the Invoice Information table)
   - product_id (Foreign Key: links to the Product Information table)
   - client_id (Foreign Key: links to the Customer Information table)
   - Quantity

In the above structure, `client_id`, `product_id`, and `invoice_id` are used as primary keys for their respective tables. <br>
These keys are unique identifiers for each record in the tables, ensuring each record can be uniquely identified.

The Foreign keys in the Sales Information entity are:
- `invoice_id` in the Invoice Information table,
- `product_id` in the Invoice Information table, and
- `client_id` in the customer Information table <br><br>

These keys are used to link the tables together. <br>
The values in these foreign key columns correspond to the values in the primary key columns of the referenced tables. <br>
This allows us to join data across multiple tables.

### Verify unique combinations

In [450]:
# # Check for any duplicates in what we presume are unique columns
# assert data['InvoiceNo'].is_unique
# assert data['CustomerID'].is_unique
# assert data['StockCode'].is_unique


In [451]:
# trys = data.drop_duplicates(subset=["InvoiceNo", "InvoiceDate"])

# # Check if the combination of InvoiceNo and InvoiceDate is unique
# is_unique = trys.duplicated(subset=["InvoiceNo", "InvoiceDate"]).any() == False

# print("The combination of InvoiceNo and InvoiceDate is unique:", is_unique)

### Customer subset

In [452]:
# SUBSET 1: customer
# First, drop duplicates based on CustomerID and Country
customer_labels = data.drop_duplicates(subset=["CustomerID", "Country"])

# Then, create a DataFrame with unique combinations of CustomerID and Country
customer = pd.DataFrame(columns=["client_id", "CustomerID", "Country"])

for i, (index, row) in enumerate(customer_labels.iterrows()):
    customer.loc[i] = {"client_id": i, "CustomerID": row["CustomerID"], "Country": row["Country"]}

customer

client_id  CustomerID         Country
0             0       17850  United Kingdom
1             1       13047  United Kingdom
2             2       12583          France
3             3       13748  United Kingdom
4             4       15100  United Kingdom
...         ...         ...             ...
4338       4338       13436  United Kingdom
4339       4339       15520  United Kingdom
4340       4340       13298  United Kingdom
4341       4341       14569  United Kingdom
4342       4342       12713         Germany

[4343 rows x 3 columns]

### Product subset

In [453]:
# SUBSET 2: product
# First, drop duplicates based on StockCode and UnitPrice
product_labels = data.drop_duplicates(subset=["StockCode", "UnitPrice"])

# Then, create a DataFrame with unique combinations of StockCode and UnitPrice
product = pd.DataFrame(columns=["product_id", "StockCode", "UnitPrice"])

for i, (index, row) in enumerate(product_labels.iterrows()):
    product.loc[i] = {"product_id": i, "StockCode": row["StockCode"], "UnitPrice": row["UnitPrice"]}

# Create a dictionary mapping StockCode and UnitPrice to Description
product_description_mapping = data.set_index(["StockCode", "UnitPrice"])["Description"].to_dict()

# Create a new column "Description" in product subset
product["Description"] = product.set_index(["StockCode", "UnitPrice"]).index.map(product_description_mapping)

product

product_id StockCode  UnitPrice                          Description
0              0     21730       4.25     frosted tlight glass star holder
1              1     22752       7.65         nesting boxes babushka 7 set
2              2     71053       3.39         moroccan metal lantern white
3              3    84029E       3.39        red heart hottie woolly white
4              4    84029G       3.39  union flag hot bottle water knitted
...          ...       ...        ...                                  ...
8398        8398     23526       3.90                 wall art dog licence
8399        8399     23535       3.90       wall art saftey safety bicycle
8400        8400     21253       0.79           stickers frame set picture
8401        8401     23843       2.08            paper little birdie craft
8402        8402     20936       1.25                 cactus forked candle

[8403 rows x 4 columns]

### Invoice subset

In [454]:
# SUBSET 3: invoice
# First, drop duplicates based on InvoiceNo and InvoiceDate
invoice_labels = data.drop_duplicates(subset=["InvoiceNo", "InvoiceDate"])

# Create a list of columns for invoice DataFrame
columns = ["invoice_id", "InvoiceNo", "InvoiceDate", "invoiceDate_norm", "Year", "YearMonth", "Month", "MonthDate", "DayofMonth", "Hour", "DayofWeek", "Month_name", "Day_name"]

# Then, create a DataFrame with the unique combinations of InvoiceNo and InvoiceDate, and the additional columns
invoice = pd.DataFrame(columns=columns)

for i, (index, row) in enumerate(invoice_labels.iterrows()):
    invoice.loc[i] = {
        "invoice_id": i, 
        "InvoiceNo": row["InvoiceNo"],  
        "InvoiceDate": row["InvoiceDate"], 
        "invoiceDate_norm": row["invoiceDate_norm"], 
        "Year": row["Year"], 
        "YearMonth": row["YearMonth"], 
        "Month": row["Month"], 
        "MonthDate": row["MonthDate"], 
        "DayofMonth": row["DayofMonth"], 
        "Hour": row["Hour"], 
        "DayofWeek": row["DayofWeek"], 
        "Month_name": row["Month_name"], 
        "Day_name": row["Day_name"]
    }

invoice

invoice_id  InvoiceNo         InvoiceDate invoiceDate_norm  Year  \
0               0     536365 2010-12-01 08:26:00       2010-12-01  2010   
1               1     536366 2010-12-01 08:28:00       2010-12-01  2010   
2               2     536367 2010-12-01 08:34:00       2010-12-01  2010   
3               3     536368 2010-12-01 08:34:00       2010-12-01  2010   
4               4     536369 2010-12-01 08:35:00       2010-12-01  2010   
...           ...        ...                 ...              ...   ...   
18444       18444     581583 2011-12-09 12:23:00       2011-12-09  2011   
18445       18445     581584 2011-12-09 12:25:00       2011-12-09  2011   
18446       18446     581585 2011-12-09 12:31:00       2011-12-09  2011   
18447       18447     581586 2011-12-09 12:49:00       2011-12-09  2011   
18448       18448     581587 2011-12-09 12:50:00       2011-12-09  2011   

      YearMonth  Month MonthDate  DayofMonth  Hour  DayofWeek Month_name  \
0       2010-12     12     12-01           1     8          2   December   
1       2010-12     12     12-01           1     8          2   December   
2       2010-12     12     12-01           1     8          2   December   
3       2010-12     12     12-01           1     8          2   December   
4       2010-12     12     12-01           1     8          2   December   
...         ...    ...       ...         ...   ...        ...        ...   
18444   2011-12     12     12-09           9    12          4   December   
18445   2011-12     12     12-09           9    12          4   December   
18446   2011-12     12     12-09           9    12          4   December   
18447   2011-12     12     12-09           9    12          4   December   
18448   2011-12     12     12-09           9    12          4   December   

        Day_name  
0      Wednesday  
1      Wednesday  
2      Wednesday  
3      Wednesday  
4      Wednesday  
...          ...  
18444     Friday  
18445     Friday  
18446     Friday  
18447     Friday  
18448     Friday  

[18449 rows x 13 columns]

### Sales subset

In [462]:
# SUBSET 4: sales
pd.set_option("display.max_columns", None)

sales = data[["InvoiceNo", "InvoiceDate", "StockCode", "Quantity", "UnitPrice", "CustomerID"]].copy()
sales = sales.merge(customer, on="CustomerID", how="left")
sales = sales.merge(product, on=["StockCode", "UnitPrice"], how="left")
sales = sales.merge(invoice, on=["InvoiceNo", "InvoiceDate"], how="left")
sample = sales.copy()
sales = sales[["invoice_id", "product_id", "client_id", "Quantity"]]
sales.index.name = "sales_id"
sales = sales.reset_index()
sales 

sales_id  invoice_id  product_id  client_id  Quantity
0              0           0           0          0         6
1              1           0           1          0         2
2              2           0           2          0         6
3              3           0           3          0         6
4              4           0           4          0         6
...          ...         ...         ...        ...       ...
387177    387177       18448         211       3254         4
387178    387178       18448         454       3254         6
387179    387179       18448        4493       3254         4
387180    387180       18448        4511       3254         4
387181    387181       18448        4494       3254         4

[387182 rows x 5 columns]

## YOU STOPPED HERE!

Looking awesome so far! <br>
Let's check our subsets

## Double check tables

In [463]:
dataframes = {"customer": customer, "invoice": invoice, "product": product, "sales": sales, "returns": returns}

for name, dataset in dataframes.items():
    print(f"{name} dataset")
    print(f"Number of rows: {len(dataset):,}")
    print(f"Number of columns: {len(dataset.columns):,}")
    display(dataset.head())
    print()

customer dataset
Number of rows: 4,343
Number of columns: 3


client_id  CustomerID         Country
0          0       17850  United Kingdom
1          1       13047  United Kingdom
2          2       12583          France
3          3       13748  United Kingdom
4          4       15100  United Kingdom


invoice dataset
Number of rows: 18,449
Number of columns: 13


invoice_id  InvoiceNo         InvoiceDate invoiceDate_norm  Year YearMonth  \
0           0     536365 2010-12-01 08:26:00       2010-12-01  2010   2010-12   
1           1     536366 2010-12-01 08:28:00       2010-12-01  2010   2010-12   
2           2     536367 2010-12-01 08:34:00       2010-12-01  2010   2010-12   
3           3     536368 2010-12-01 08:34:00       2010-12-01  2010   2010-12   
4           4     536369 2010-12-01 08:35:00       2010-12-01  2010   2010-12   

   Month MonthDate  DayofMonth  Hour  DayofWeek Month_name   Day_name  
0     12     12-01           1     8          2   December  Wednesday  
1     12     12-01           1     8          2   December  Wednesday  
2     12     12-01           1     8          2   December  Wednesday  
3     12     12-01           1     8          2   December  Wednesday  
4     12     12-01           1     8          2   December  Wednesday


product dataset
Number of rows: 8,403
Number of columns: 4


product_id StockCode  UnitPrice                          Description
0           0     21730       4.25     frosted tlight glass star holder
1           1     22752       7.65         nesting boxes babushka 7 set
2           2     71053       3.39         moroccan metal lantern white
3           3    84029E       3.39        red heart hottie woolly white
4           4    84029G       3.39  union flag hot bottle water knitted


sales dataset
Number of rows: 387,182
Number of columns: 5


sales_id  invoice_id  product_id  client_id  Quantity
0         0           0           0          0         6
1         1           0           1          0         2
2         2           0           2          0         6
3         3           0           3          0         6
4         4           0           4          0         6


returns dataset
Number of rows: 8,551
Number of columns: 19


InvoiceNo         InvoiceDate StockCode                    Description  \
386360   C536379 2010-12-01 09:41:00         D                       discount   
386361   C536383 2010-12-01 09:49:00    35004C    3 coloured flying ducks set   
386362   C536391 2010-12-01 10:24:00     21484    hot grey bottle water chick   
386363   C536391 2010-12-01 10:24:00     21980  12 red pack retrospot tissues   
386364   C536391 2010-12-01 10:24:00     21983   12 paisley pack blue tissues   

        Quantity  UnitPrice  Revenue  CustomerID         Country  \
386360        -1      27.50   -27.50       14527  United Kingdom   
386361        -1       4.65    -4.65       15311  United Kingdom   
386362       -12       3.45   -41.40       17548  United Kingdom   
386363       -24       0.29    -6.96       17548  United Kingdom   
386364       -24       0.29    -6.96       17548  United Kingdom   

       invoiceDate_norm  Year YearMonth  Month MonthDate  DayofMonth  Hour  \
386360       2010-12-01  2010   2010-12     12     12-01           1     9   
386361       2010-12-01  2010   2010-12     12     12-01           1     9   
386362       2010-12-01  2010   2010-12     12     12-01           1    10   
386363       2010-12-01  2010   2010-12     12     12-01           1    10   
386364       2010-12-01  2010   2010-12     12     12-01           1    10   

        DayofWeek Month_name   Day_name  
386360          2   December  Wednesday  
386361          2   December  Wednesday  
386362          2   December  Wednesday  
386363          2   December  Wednesday  
386364          2   December  Wednesday

Okay, looking pretty I guess. <br>
Let's export our main dataset and them subsets into csv files and prepare them for SQL

## csv files

In [464]:
data.to_csv("data.csv")
customer.to_csv("customer.csv")
invoice.to_csv("invoice.csv")
product.to_csv("product.csv")
sales.to_csv("sales.csv")
returns.to_csv("returns.csv")

## SQL tables

In [470]:
import getpass
import pymysql.cursors
from sqlalchemy import create_engine
from sqlalchemy import text

# Prompt user to enter MySQL root password
sql_pass = getpass.getpass()

# Create connection string and engine to connect to MySQL database
connection_string = "mysql+pymysql://root:" + sql_pass + "@localhost:3306/TheFinal"
engine = create_engine(connection_string)

# Write DataFrames to SQL
customer.to_sql("customer", engine, "TheFinal", if_exists="replace", index=False)
invoice.to_sql("invoice", engine, "TheFinal", if_exists="replace", index=False)
product.to_sql("product", engine, "TheFinal", if_exists="replace", index=False)
sales.to_sql("sales", engine, "TheFinal", if_exists="replace", index=False)
returns.to_sql("returns", engine, "TheFinal", if_exists="replace", index=False)

# Define primary keys using raw SQL
with engine.connect() as conn:
    conn.execute("ALTER TABLE customer ADD PRIMARY KEY (client_id);")
    conn.execute("ALTER TABLE invoice ADD PRIMARY KEY (invoice_id);")
    conn.execute("ALTER TABLE product ADD PRIMARY KEY (product_id);")
    conn.execute("ALTER TABLE sales ADD PRIMARY KEY (sales_id);")

# Define auto-incremented primary keys using raw SQL
with engine.connect() as conn:
    conn.execute("ALTER TABLE returns ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY;")

# Move Primary Keys in the first column
with engine.connect() as conn:
    conn.execute("ALTER TABLE returns MODIFY id INT AUTO_INCREMENT FIRST;")

# Specify Foreign Keys in the sales table
with engine.connect() as conn:
    conn.execute("ALTER TABLE sales ADD FOREIGN KEY (client_id) REFERENCES customer(client_id);")
    conn.execute("ALTER TABLE sales ADD FOREIGN KEY (invoice_id) REFERENCES invoice(invoice_id);")
    conn.execute("ALTER TABLE sales ADD FOREIGN KEY (product_id) REFERENCES product(product_id);")

# Exploratory Data Analysis
![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)